"""Seed a golden-set YAML template from rows in the interactions table.

Usage (from `/app` inside the backend container):

    python -m scripts.seed_golden --output evals/scenarios/from_history.yaml
    python -m scripts.seed_golden --channel chat --limit 30 \\
        --output evals/scenarios/from_history.yaml

Output is a valid YAML document, but with the `expect:` block left empty
for each entry — the user fills those in by hand. Observed tools and
payload type are emitted as inline comments so the human labeler has
context without having to open the DB.
"""

import argparse
import asyncio
import logging
import re
import sys
from pathlib import Path

from sqlalchemy import select

from app.database import async_session_maker
from app.models.tables import Interaction

logger = logging.getLogger(__name__)


def _safe_id(user_message: str, fallback: str) -> str:
    """Produce a filesystem-safe scenario id from the message prefix."""
    snippet = re.sub(r"[^a-z0-9]+", "_", user_message.lower()).strip("_")[:40]
    return snippet or fallback


def _yaml_quote(text: str) -> str:
    """Double-quote a string for embedding in YAML, escaping internal quotes."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


async def _fetch(channel: str | None, limit: int) -> list[Interaction]:
    async with async_session_maker() as db:
        stmt = select(Interaction).order_by(Interaction.created_at.desc()).limit(limit)
        if channel:
            stmt = stmt.where(Interaction.channel == channel)
        rows = (await db.execute(stmt)).scalars().all()
    return list(rows)


def _render(rows: list[Interaction]) -> str:
    lines: list[str] = [
        "# Generated by scripts/seed_golden.py from the interactions table.",
        "# Fill in the `expect:` blocks to turn these into real assertions.",
        "# Each entry supports:",
        "#   components_any_of: list of component names (at least one must be active)",
        "#   tools_called_any_of: list of tool names (at least one must be called)",
        "#   payload_type: exact match on structured_payload.type",
        "#   confirmation_required: true | false",
        "",
    ]

    for row in rows:
        if not row.user_message:
            continue
        scenario_id = _safe_id(row.user_message, fallback=f"interaction_{row.id}")
        actions = row.actions_taken or []
        observed_tools = sorted({a.get("tool_name") for a in actions if a.get("tool_name")})
        resp = row.assistant_response or {}
        payload = resp.get("structured_payload") or {}
        observed_payload_type = payload.get("type") if isinstance(payload, dict) else None
        observed_confirmation = bool(resp.get("confirmation_required"))

        lines.append(f"- id: {scenario_id}")
        lines.append(f"  user_message: {_yaml_quote(row.user_message)}")
        lines.append(f"  # source_interaction_id: {row.id}")
        lines.append(f"  # source_channel: {row.channel}")
        if observed_tools:
            lines.append(f"  # observed_tools: {observed_tools}")
        if observed_payload_type:
            lines.append(f"  # observed_payload_type: {observed_payload_type}")
        if observed_confirmation:
            lines.append(f"  # observed_confirmation_required: true")
        lines.append("  expect: {}")
        lines.append("")

    return "\n".join(lines)


async def _run(channel: str | None, limit: int, output: Path) -> int:
    rows = await _fetch(channel, limit)
    if not rows:
        logger.warning("No interactions found for channel=%s", channel)
        return 1
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_render(rows))
    logger.info("Wrote %d scenarios to %s", len(rows), output)
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--channel", default=None, help="Filter by interaction channel (e.g. chat)")
    parser.add_argument("--limit", type=int, default=30)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s [%(name)s] %(message)s",
    )

    sys.exit(asyncio.run(_run(args.channel, args.limit, args.output)))


if __name__ == "__main__":
    main()
